public class ProviderResult {
    public Boolean success;
    public String errorMessage;

    public Boolean policyActive;
    public String activeDate;
    public String planName;
    public String employer;
    public Boolean outOfNetwork;

    public String subscriberAddress;
    public String subscriberCity;
    public String subscriberState;
    public String subscriberZip;

    public String patientDob;
    public String patientAddress1;
    public String patientAddress2;
    public String patientCity;
    public String patientState;
    public String patientZip;

    public String planStatus;
    public String outOfNetworkBenefits;
    public Date effectiveDate;
    public String insurancePolicy;
    public String vobId;

    public Decimal dedInn;
    public Decimal dedMetInn;
    public Decimal oopInn;
    public Decimal oopMetInn;
    public Decimal copayInn;
    public String indOrFamInn;

    public Decimal dedOon;
    public Decimal dedMetOon;
    public Decimal oopOon;
    public Decimal oopMetOon;
    public Decimal copayOon;
    public String indOrFamOon;

    public Decimal covgPercInn;
    public Decimal covgPercOon;
    public String hasInnOopMax;
    public String hasOonOopMax;
}